### ISSUE TITLE
engine 连接不到运程控制台

### ISSUE THREAD

**Issue by u-nine** [Monibuca/engine#118]
Linux version 3.10.0-1160.119.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 4 14:43:51 UTC 2024
engine:v4.15.2

config.yaml:
```
global:
  disableall: false # 是否禁用所有插件
  loglang: zh # 日志语言，可选值：zh,en
  loglevel: info # 日志级别，可选值：debug,info,warn,error,panic,fatal
  http:
    listenaddr: :8080 # 网关地址，用于访问API
    listenaddrtls: :8443 # 用于HTTPS方式访问API的端口配置
    certfile: ""
    keyfile: ""
    cors: true # 是否自动添加cors头
    username: "" # 用户名和密码，用于API访问时的基本身份认证
    password: ""
    readtimeout: 0 # 读超时时间
    writetimeout: 0 # 写超时时间
    idletimeout: 0 # 空闲超时时间
  publish:
    pubaudio: true # 是否发布音频流
    pubvideo: true # 是否发布视频流
    kickexist: false # 剔出已经存在的发布者，用于顶替原有发布者
    insertsei: false # 是否启用插入SEI功能
    publishtimeout: 10s # 发布流默认过期时间，超过该时间发布者没有恢复流将被删除
    idletimeout: 0 # 发布者空闲超时时间，超过该时间发布者没有任何操作将被删除，0为关闭该功能
    delayclosetimeout: 0 # 自动关闭触发后延迟的时间(期间内如果有新的订阅则取消触发关闭)，0为关闭该功能，保持连接。
    waitclosetimeout: 0 # 发布者断开后等待时间，超过该时间发布者没有恢复流将被删除，0为关闭该功能，由订阅者决定是否删除
    buffertime: 0 # 缓存时间，用于时光回溯，0为关闭缓存
    key: "" # 订阅者鉴权秘钥
    secretargname: secret # 订阅者鉴权参数名
    expireargname: expire # 订阅者鉴权过期时间参数名
    speedlimit: 500ms # 限速超时时间0为不限速，对于读取文件这类流需要限速，否则读取过快
  subscribe:
    subaudio: true # 是否订阅音频流
    subvideo: true # 是否订阅视频流
    subaudioargname: ats # 订阅音频轨道参数名
    subvideoargname: vts # 订阅视频轨道参数名
    subdataargname: dts # 订阅数据轨道参数名
    subaudiotracks: [] # 订阅音频轨道名称列表
    subvideotracks: [] # 订阅视频轨道名称列表
    submode: 0 # 订阅模式，0为跳帧追赶模式，1为不追赶（多用于录制），2为时光回溯模式
    syncmode: 0 # 音视频同步模式，0 为按照时间戳同步，1 为按照写入时间同步
    iframeonly: false # 只订阅关键帧
    waittimeout: 10s # 等待发布者的超时时间，用于订阅尚未发布的流
    writebuffersize: 0 # 订阅者写缓存大小，用于减少io次数，但可能影响实时性
    key: "" # 订阅者鉴权秘钥
    secretargname: secret # 订阅者鉴权参数名
    expireargname: expire # 订阅者鉴权过期时间参数名
    internal: false # 是否内部订阅，内部订阅不会触发发布者自动断开功能
  enableavcc: true # 启用AVCC格式缓存，用于rtmp协议
  enablertp: true # 启用rtp格式缓存，用于rtsp、websocket、gb28181协议
  enableauth: true # 启用鉴权,详细查看鉴权机制
  enablesubevent: true # 启用订阅事件，用于订阅者上下线事件,关闭可以提高性能
  rtpreorderbufferlen: 50 # rtp乱序重排缓存长度
  eventbussize: 10 # 事件总线缓存大小，事件较多时容易堵阻塞线程，需要增大缓存
  poolsize: 0 # 内存池大小，高并发需要提高性能可以加大内存池，减少 GC
  pulseinterval: 5s # 心跳事件间隔时间
  console:
    server: console.monibuca.com:44944 # 连接远程控制台的地址
    secret: "4ed7dc262c2f5d69930e599333076321" # 远程控制台的秘钥
    publicaddr: "27.128.174.224" # 实例公网地址，提供远程控制台访问的地址，不配置的话使用自动识别的地址
    publicaddrtls: "" # 实例公网地址，提供远程控制台访问的地址，不配置的话使用自动识别的地址（https）

hls:
  enable: false
monitor:
  enable: false
```

问题：
![image](https://github.com/user-attachments/assets/3c80e002-6695-42de-9675-af3df39ac084)

**Comment by langhuihui** [comment]
你把配置文件里面内容都删除，只保留需要修改的部分

**Comment by langhuihui** [comment]
另外可能就是你的网络屏蔽了 udp 请求

**Comment by u-nine** [comment]
iptables -L OUTPUT -v -n
```
Chain OUTPUT (policy ACCEPT 673 packets, 686K bytes)
 pkts bytes target     prot opt in     out     source               destination         
    2   523 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0
```

config.yaml已经修改
```
global:
  loglevel: info # 日志级别，可选值：debug,info,warn,error,panic,fatal
  console:
    server: console.monibuca.com:44944 # 连接远程控制台的地址
    secret: "4ed7dc262c2f5d69930e599333076321" # 远程控制台的秘钥
    publicaddr: "27.128.174.224" # 实例公网地址，提供远程控制台访问的地址，不配置的话使用自动识别的地址
hls:
  enable: false
monitor:
  enable: false
```
![image](https://github.com/user-attachments/assets/a87a02db-7ff7-418c-b433-911d6cfc5217)

仔细检查了一下，已经把防火墙关了也还是连不上
